export enum ActionType {
  EVENT_LIST_REQUEST = 'EVENT_LIST_REQUEST',
  EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS',
  EVENT_LIST_FAIL = 'EVENT_LIST_FAIL',
  EVENT_OUTCOME_REQUEST = 'EVENT_OUTCOME_REQUEST',
  EVENT_OUTCOME_SUCCESS = 'EVENT_OUTCOME_SUCCESS',
  EVENT_OUTCOME_FAIL = 'EVENT_OUTCOME_FAIL',
}
