export enum ActionType {
  EVENT_LIST_REQUEST = 'EVENT_LIST_REQUEST',
  EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS',
  EVENT_LIST_FAIL = 'EVENT_LIST_FAIL',
  EVENT_OUTCOME_REQUEST = 'EVENT_OUTCOME_REQUEST',
  EVENT_OUTCOME_SUCCESS = 'EVENT_OUTCOME_SUCCESS',
  EVENT_OUTCOME_FAIL = 'EVENT_OUTCOME_FAIL',
  EVENT_MARKET_DATA_REQUEST = 'EVENT_MARKET_DATA_REQUEST',
  EVENT_MARKET_DATA_SUCCESS = 'EVENT_MARKET_DATA_SUCCESS',
  EVENT_MARKET_DATA_FAIL = 'EVENT_MARKET_DATA_FAIL',
  EVENT_DATA_REQUEST = 'EVENT_DATA_REQUEST',
  EVENT_DATA_SUCCESS = 'EVENT_DATA_SUCCESS',
  EVENT_DATA_FAIL = 'EVENT_DATA_FAIL',
}

// export enum MarketDataConstants {

// }
